

ANCHO = 1128  
ALTO = 634  


#!!!!!!!!! POSICIONES !!!!!!!!!!!!
PORCENTAJE_TITULO = 20
PORCENTAJE_INICIAR = 60
PORCENTAJE_TITULO_MENU = 10
PORCENTAJE_BOTON_JUGAR_Y = 33
PORCENTAJE_BOTON_PUNTAJE_Y = 48
PORCENTAJE_BOTON_DIFICULTAD_Y = 63
PORCENTAJE_BOTON_SALIR_Y = 78
PORCENTAJE_TEXTO_DIFICULTAD = 0
PORCENTAJE_PRIMERA_CELDA = 5
PORCENTAJE_BOTON_HOME_X = 63
PORCENTAJE_BOTONES_SUDO_Y = 75
PORCENTAJE_BOTON_REINICIAR_X = 85
PORCENTAJE_TIM_ERR_X = 63
PORCENTAJE_TIMER_Y = 14
PORCENTAJE_ERRORES_Y = 29
POSICION_RECT_BLANCO_X = 60
POSICION_RECT_BLANCO_Y = 10
PORCENTAJE_RADIO_BOTONES = 2
PORCENTAJE_BOTON_GOMA_X = 74
PORCENTAJE_Y_NIVELES = 69
PORCENTAJE_WIN = 20
PORCENTAJE_BORDES = 1
PORCENTAJE_Y_GANADOR = 15
PORCENTAJE_Y_USER = 50
PORCENTAJE_Y_TXT_RANKING = 13    
PORCENTAJE_Y_RANKING = 8        
PORCENTAJE_X_NOMBRE = 13
PORCENTAJE_X_PUNTAJE = 80
PORCENTAJE_Y_NOMBRE_PUNTAJE = 29
PORCENTAJE_X_VOLVER = 94
PORCENTAJE_Y_VOLVER = 1
PORCENTAJE_Y_PUNTAJE_MOSTRADO = 70
PORCENTAJE_Y_TOP_NOM_PUNT = 20
PORCENTAJE_X_TOP = 12
PORCENTAJE_X_NOMBRE_RANKING = 20
PORCENTAJE_X_TU_PUNTAJE = 77
PORCENTAJE_Y_PUNTAJE_MOSTRADO = 68




#!!!!!!!!!! TAMAÑOS !!!!!!!!!!!!!
SIZE_W_TIM_ERR = 30
SIZE_H_TIM_ERR = 12
SIZE_W_BOTONES_JUEGO = 8
SIZE_H_BOTONES_JUEGO = 13
SIZE_H_PUNTAJE = 10
SIZE_H_IMAGENES_JUEGO = 8
SIZE_BOT_MENU_W = 17
SIZE_BOT_MENU_H = 12
SIZE_TXT_TITULO = 20
SIZE_TXT_ENTER = 5
SIZE_TXT_TITULO_MENU = 12
SIZE_TXT_VERSION = 3
SIZE_TXTS_MENU = 5
SIZE_TXT_DIFICULTAD = 4
SIZE_TXT_TIM_ERR = 6
SIZE_TXT_NUM_CELDA = 8
PORCENTAJE_RADIO_BLANCO = 5
SIZE_RECT_BLANCO_W = 36
SIZE_RECT_BLANCO_H = 82
SIZE_CELDA_W = 5.6
SIZE_CELDA_H = 9.9
SIZE_W_GANADOR = 60
SIZE_H_GANADOR = 65
SIZE_W_USER = 37
SIZE_H_USER = 13
SIZE_TXT_RANKING = 10
SIZE_W_RANKING = 85
SIZE_H_RANKING = 85
SIZE_TXT_JUGADORES = 4
SIZE_ESPACIADO_RANKING = 2
SIZE_H_VOLVER_RANKING = 4
SIZE_W_RECT_VOLVER = 5
SIZE_H_RECT_VOLVER = 8
SIZE_TXT_WIN = 12
SIZE_TXT_NICK = 7
SIZE_TXT_TOP_NOM_PUNT = 3
SIZE_TXT_TU_PUNTAJE = 5
SIZE_TXT_USER_INGRE = 6

NEGRO = (0, 0, 0)
AZUL = (15, 74, 115) 
BLANCO = (255, 255, 255)
CELESTE_CLARO = (158, 200, 255) 
GRIS = (219, 217, 217)
AZUL_OSCURO = (34, 51, 69)
VERDE = (22, 153, 15)
ROJO = (194, 21, 21)